working_directory = "None"
# live_config_reload = true

[window]
  dynamic_title = true

[scrolling]
  history = 100000

[selection]
  semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
  save_to_clipboard = true

[cursor]
  style = "Block"
  unfocused_hollow = true
  vi_mode_style = "Underline"

[mouse]
  hide_when_typing = true
